-- 插入成员数据的 SQL 脚本
-- 
-- 注意：
-- 1. `password_hash` 和 `email` 字段在此脚本中填充为占位符数据，因为原始数据中不包含这些信息。
-- 2. `moetran_id` 字段是根据昵称生成的唯一 ID。
-- 3. `labors` 字段是根据人员的角色（如修图、美工、翻译等）计算出的位掩码，已更新为最新定义。
-- 4. `remark` 字段合并了原始数据中所有相关的备注信息，并为英翻人员添加了“英翻”标识。
-- 5. `last_active` 字段统一设为 `now()`，`deleted_at` 字段统一设为 `NULL`。
-- 6. `created_at` 和 `updated_at` 字段使用数据库的 `now()` 函数自动填充。
-- 7. `poplar_is_admin` 字段默认设置为 FALSE。

-- 可选：如果您想在每次运行时清空表，可以取消注释以下行。
-- TRUNCATE TABLE members RESTART IDENTITY CASCADE;

INSERT INTO members (
    nickname, 
    email, 
    password_hash, 
    moetran_id, 
    poplar_is_admin, 
    labors, 
    remark, 
    last_active, 
    deleted_at
) VALUES
('杨声器', 'yangshengqi@example.com', 'dummy_hash_for_yangshengqi', 'moetran_001', FALSE, 518, NULL, now(), NULL),
('沙发垫', 'shafadian@example.com', 'dummy_hash_for_shafadian', 'moetran_002', FALSE, 16, NULL, now(), NULL),
('落叶', 'luoye@example.com', 'dummy_hash_for_luoye', 'moetran_003', FALSE, 16 | 128, '2.17丸玖', now(), NULL),
('残阳', 'canyang@example.com', 'dummy_hash_for_canyang', 'moetran_004', FALSE, 16 | 128, '6.25', now(), NULL),
('不会真的有人喜欢画画吧', 'buhuizhendeyourenxihuanhuahuaba@example.com', 'dummy_hash_for_buhuizhendeyourenxihuanhuahuaba', 'moetran_005', FALSE, 16 | 8, NULL, now(), NULL),
('迪奥大人', 'diaodaren@example.com', 'dummy_hash_for_diaodaren', 'moetran_006', FALSE, 16 | 8, NULL, now(), NULL),
('夜末Nighendt', 'yemonihendt@example.com', 'dummy_hash_for_yemonihendt', 'moetran_007', FALSE, 16, NULL, now(), NULL),
('千新星_Kilonova', 'qianxinxing_kilonova@example.com', 'dummy_hash_for_qianxinxing_kilonova', 'moetran_008', FALSE, 8, NULL, now(), NULL),
('璃.', 'li.@example.com', 'dummy_hash_for_li.', 'moetran_009', FALSE, 8 | 128, '6.14', now(), NULL),
('夜のない国', 'yorunonaikuni@example.com', 'dummy_hash_for_yorunonaikuni', 'moetran_010', FALSE, 32, NULL, now(), NULL),
('gh', 'gh@example.com', 'dummy_hash_for_gh', 'moetran_011', FALSE, 32, NULL, now(), NULL),
('wood', 'wood@example.com', 'dummy_hash_for_wood', 'moetran_012', FALSE, 32, 'n2', now(), NULL),
('椿', 'chun@example.com', 'dummy_hash_for_chun', 'moetran_013', FALSE, 32, 'n2', now(), NULL),
('糖饺', 'tangjiao@example.com', 'dummy_hash_for_tangjiao', 'moetran_014', FALSE, 32, 'n1', now(), NULL),
('Marasy', 'marasy@example.com', 'dummy_hash_for_marasy', 'moetran_015', FALSE, 32, NULL, now(), NULL),
('借过', 'jiegou@example.com', 'dummy_hash_for_jiegou', 'moetran_016', FALSE, 32, NULL, now(), NULL),
('PriZm', 'prizm@example.com', 'dummy_hash_for_prizm', 'moetran_017', FALSE, 32, NULL, now(), NULL),
('さかき', 'sakaki@example.com', 'dummy_hash_for_sakaki', 'moetran_018', FALSE, 32 | 128, '栗悟饭', now(), NULL),
('咫墨离音', 'zhimoliyin@example.com', 'dummy_hash_for_zhimoliyin', 'moetran_019', FALSE, 32, NULL, now(), NULL),
('落日神殇', 'luorishenshang@example.com', 'dummy_hash_for_luorishenshang', 'moetran_020', FALSE, 32, 'N1', now(), NULL),
('不知道取什么名字', 'buzhidaoqushenmemingzi@example.com', 'dummy_hash_for_buzhidaoqushenmemingzi', 'moetran_021', FALSE, 32, NULL, now(), NULL),
('梦佬', 'menglao@example.com', 'dummy_hash_for_menglao', 'moetran_022', FALSE, 32, 'n1', now(), NULL),
('常春藤', 'changchunteng@example.com', 'dummy_hash_for_changchunteng', 'moetran_023', FALSE, 32, 'n2', now(), NULL),
('探戈黄瓜', 'tangeguagua@example.com', 'dummy_hash_for_tangeguagua', 'moetran_024', FALSE, 32, NULL, now(), NULL),
('四方（yeega）', 'sifangyega@example.com', 'dummy_hash_for_sifangyega', 'moetran_025', FALSE, 32, 'n2', now(), NULL),
('雪月涯', 'xueyueya@example.com', 'dummy_hash_for_xueyueya', 'moetran_026', FALSE, 32, NULL, now(), NULL),
('油と塩が混ぜたもの', 'yutoshigamazetamono@example.com', 'dummy_hash_for_yutoshigamazetamono', 'moetran_027', FALSE, 32, NULL, now(), NULL),
('シンクロ', 'shinikuro@example.com', 'dummy_hash_for_shinikuro', 'moetran_028', FALSE, 32, NULL, now(), NULL),
('MoX', 'mox@example.com', 'dummy_hash_for_mox', 'moetran_029', FALSE, 32, 'n1', now(), NULL),
('红叶', 'hongye@example.com', 'dummy_hash_for_hongye', 'moetran_030', FALSE, 32, 'n1', now(), NULL),
('纪念', 'jinian@example.com', 'dummy_hash_for_jinian', 'moetran_031', FALSE, 32, NULL, now(), NULL),
('芙兰球', 'fulanqiu@example.com', 'dummy_hash_for_fulanqiu', 'moetran_032', FALSE, 32, NULL, now(), NULL),
('若辞', 'ruoci@example.com', 'dummy_hash_for_ruoci', 'moetran_033', FALSE, 32, NULL, now(), NULL),
('Ene', 'ene@example.com', 'dummy_hash_for_ene', 'moetran_034', FALSE, 32, 'N1', now(), NULL),
('kuroroma', 'kuroroma@example.com', 'dummy_hash_for_kuroroma', 'moetran_035', FALSE, 32, NULL, now(), NULL),
('秘封', 'mifeng@example.com', 'dummy_hash_for_mifeng', 'moetran_036', FALSE, 32, NULL, now(), NULL),
('lios（江灯）', 'liosjiangdeng@example.com', 'dummy_hash_for_liosjiangdeng', 'moetran_037', FALSE, 32, NULL, now(), NULL),
('好多线啊', 'haoduoxiana@example.com', 'dummy_hash_for_haoduoxiana', 'moetran_038', FALSE, 32 | 128, '1.13', now(), NULL),
('天痕', 'tianhen@example.com', 'dummy_hash_for_tianhen', 'moetran_039', FALSE, 32 | 128, '1.13星尘王大炮, 夏目标记', now(), NULL),
('Doyouyee', 'doyouyee@example.com', 'dummy_hash_for_doyouyee', 'moetran_040', FALSE, 32, NULL, now(), NULL),
('冰殇千华', 'bingshangqianhua@example.com', 'dummy_hash_for_bingshangqianhua', 'moetran_041', FALSE, 32, NULL, now(), NULL),
('叉子', 'chazi@example.com', 'dummy_hash_for_chazi', 'moetran_042', FALSE, 32, NULL, now(), NULL),
('shenziyun', 'shenziyun@example.com', 'dummy_hash_for_shenziyun', 'moetran_043', FALSE, 32 | 128, '1.13丸玖', now(), NULL),
('ozz', 'ozz@example.com', 'dummy_hash_for_ozz', 'moetran_044', FALSE, 32, 'n1', now(), NULL),
('祈望银河', 'qiwangyinhe@example.com', 'dummy_hash_for_qiwangyinhe', 'moetran_045', FALSE, 32, NULL, now(), NULL),
('千明羽沫', 'qianmingyumo@example.com', 'dummy_hash_for_qianmingyumo', 'moetran_046', FALSE, 32, NULL, now(), NULL),
('1キュ８４', '1kyu84@example.com', 'dummy_hash_for_1kyu84', 'moetran_047', FALSE, 32, NULL, now(), NULL),
('shepherd', 'shepherd@example.com', 'dummy_hash_for_shepherd', 'moetran_048', FALSE, 32, NULL, now(), NULL),
('蒟蒻LC', 'jurouLC@example.com', 'dummy_hash_for_jurouLC', 'moetran_049', FALSE, 32, NULL, now(), NULL),
('爱情的终极形式是ntr', 'aiqingdezhongjixingshishintr@example.com', 'dummy_hash_for_aiqingdezhongjixingshishintr', 'moetran_050', FALSE, 32, NULL, now(), NULL),
('Zealot', 'zealot@example.com', 'dummy_hash_for_zealot', 'moetran_051', FALSE, 32, NULL, now(), NULL),
('子城', 'zicheng@example.com', 'dummy_hash_for_zicheng', 'moetran_052', FALSE, 32, NULL, now(), NULL),
('响月', 'xiangyue@example.com', 'dummy_hash_for_xiangyue', 'moetran_053', FALSE, 32, NULL, now(), NULL),
('莲岸三代式', 'lianansandaishi@example.com', 'dummy_hash_for_lianansandaishi', 'moetran_054', FALSE, 32, NULL, now(), NULL),
('梦焕', 'menghuan@example.com', 'dummy_hash_for_menghuan', 'moetran_055', FALSE, 32, NULL, now(), NULL),
('雪月', 'xueyue@example.com', 'dummy_hash_for_xueyue', 'moetran_056', FALSE, 32, NULL, now(), NULL),
('魔师', 'moshi@example.com', 'dummy_hash_for_moshi', 'moetran_057', FALSE, 32, NULL, now(), NULL),
('香粑粑', 'xiangbaba@example.com', 'dummy_hash_for_xiangbaba', 'moetran_058', FALSE, 32, NULL, now(), NULL),
('古巴比伦', 'gubabilun@example.com', 'dummy_hash_for_gubabilun', 'moetran_059', FALSE, 32, NULL, now(), NULL),
('Yk', 'yk@example.com', 'dummy_hash_for_yk', 'moetran_060', FALSE, 32, NULL, now(), NULL),
('乐楽樂', 'lelele@example.com', 'dummy_hash_for_lelele', 'moetran_061', FALSE, 32, NULL, now(), NULL),
('流星メテエシカ', 'liuxingmeteishika@example.com', 'dummy_hash_for_liuxingmeteishika', 'moetran_062', FALSE, 32, 'n2', now(), NULL),
('泛素', 'fansu@example.com', 'dummy_hash_for_fansu', 'moetran_063', FALSE, 32, NULL, now(), NULL),
('休比', 'xiubi@example.com', 'dummy_hash_for_xiubi', 'moetran_064', FALSE, 32, NULL, now(), NULL),
('朧月', 'longyue@example.com', 'dummy_hash_for_longyue', 'moetran_065', FALSE, 32, NULL, now(), NULL),
('翔Sean', 'xiangsean@example.com', 'dummy_hash_for_xiangsean', 'moetran_066', FALSE, 32, NULL, now(), NULL),
('蒲盐', 'puyan@example.com', 'dummy_hash_for_puyan', 'moetran_067', FALSE, 32, '·48-', now(), NULL),
('Ivy', 'ivy@example.com', 'dummy_hash_for_ivy', 'moetran_068', FALSE, 32, NULL, now(), NULL),
('浅あ然', 'qianaran@example.com', 'dummy_hash_for_qianaran', 'moetran_069', FALSE, 32, NULL, now(), NULL),
('义薄云天的智障', 'yiboyuntiandezhizhang@example.com', 'dummy_hash_for_yiboyuntiandezhizhang', 'moetran_070', FALSE, 32, 'N2', now(), NULL),
('akasi', 'akasi@example.com', 'dummy_hash_for_akasi', 'moetran_071', FALSE, 32, 'n1', now(), NULL),
('盾娘', 'dunniang@example.com', 'dummy_hash_for_dunniang', 'moetran_072', FALSE, 32, 'n2', now(), NULL),
('七佰', 'qibai@example.com', 'dummy_hash_for_qibai', 'moetran_073', FALSE, 32, 'n1', now(), NULL),
('粑拉', 'bala@example.com', 'dummy_hash_for_bala', 'moetran_074', FALSE, 32, 'N1', now(), NULL),
('思空', 'sikong@example.com', 'dummy_hash_for_sikong', 'moetran_075', FALSE, 32, 'N1', now(), NULL),
('一二三四五六', 'yiersansiwuliu@example.com', 'dummy_hash_for_yiersansiwuliu', 'moetran_076', FALSE, 32, 'N1', now(), NULL),
('camille', 'camille@example.com', 'dummy_hash_for_camille', 'moetran_077', FALSE, 32, 'n2', now(), NULL),
('拭雲影', 'shiyunying@example.com', 'dummy_hash_for_shiyunying', 'moetran_078', FALSE, 32, 'N1', now(), NULL),
('予浅', 'yuqian@example.com', 'dummy_hash_for_yuqian', 'moetran_079', FALSE, 32, 'N2', now(), NULL),
('宵和露月', 'xiaoheluyue@example.com', 'dummy_hash_for_xiaoheluyue', 'moetran_080', FALSE, 32, 'N2', now(), NULL),
('卡弥耶', 'kamiye@example.com', 'dummy_hash_for_kamiye', 'moetran_081', FALSE, 32, 'N2', now(), NULL),
('柏芊', 'baiqian@example.com', 'dummy_hash_for_baiqian', 'moetran_082', FALSE, 32, 'N2', now(), NULL),
('夜空ツバサ', 'yakotsubasa@example.com', 'dummy_hash_for_yakotsubasa', 'moetran_083', FALSE, 32, 'N2', now(), NULL),
('菠萝包', 'boluobao@example.com', 'dummy_hash_for_boluobao', 'moetran_084', FALSE, 32, 'N2', now(), NULL),
('白虎野', 'baihuye@example.com', 'dummy_hash_for_baihuye', 'moetran_085', FALSE, 32, 'N1', now(), NULL),
('那白', 'nabai@example.com', 'dummy_hash_for_nabai', 'moetran_086', FALSE, 32, 'N1', now(), NULL),
('纱露朵', 'shaluduo@example.com', 'dummy_hash_for_shaluduo', 'moetran_087', FALSE, 32, NULL, now(), NULL),
('薪岩', 'xinyan@example.com', 'dummy_hash_for_xinyan', 'moetran_088', FALSE, 32, 'N2', now(), NULL),
('unkoおいしい', 'unkooishii@example.com', 'dummy_hash_for_unkooishii', 'moetran_089', FALSE, 32, NULL, now(), NULL),
('pure_blue', 'pure_blue@example.com', 'dummy_hash_for_pure_blue', 'moetran_090', FALSE, 32 | 128, '无,无,无,来者不拒,', now(), NULL),
('pko', 'pko@example.com', 'dummy_hash_for_pko', 'moetran_091', FALSE, 32, 'N1', now(), NULL),
('Debu冒险家', 'debumaoxianjia@example.com', 'dummy_hash_for_debumaoxianjia', 'moetran_092', FALSE, 64, '我,是,男,娘,', now(), NULL),
('电容', 'dianrong@example.com', 'dummy_hash_for_dianrong', 'moetran_093', FALSE, 64, '他,是,男,娘,', now(), NULL),
('灰暗天穹', 'huianqianqiong@example.com', 'dummy_hash_for_huianqianqiong', 'moetran_094', FALSE, 64, '你,是,男,娘,', now(), NULL),
('チェンリアク', 'chenliaku@example.com', 'dummy_hash_for_chenliaku', 'moetran_095', FALSE, 64, NULL, now(), NULL),
('はばやし', 'habayashu@example.com', 'dummy_hash_for_habayashu', 'moetran_096', FALSE, 64, NULL, now(), NULL),
('Arsked', 'arsked@example.com', 'dummy_hash_for_arsked', 'moetran_097', FALSE, 64, NULL, now(), NULL),
('moooooo', 'moooooo@example.com', 'dummy_hash_for_moooooo', 'moetran_098', FALSE, 64, NULL, now(), NULL),
('若叶', 'ruoye@example.com', 'dummy_hash_for_ruoye', 'moetran_099', FALSE, 64, '兰陵w', now(), NULL),
('凤凰院咲夜', 'fenghuangyuanxiaoye@example.com', 'dummy_hash_for_fenghuangyuanxiaoye', 'moetran_100', FALSE, 64, NULL, now(), NULL),
('白柳', 'bailiu@example.com', 'dummy_hash_for_bailiu', 'moetran_101', FALSE, 64, NULL, now(), NULL),
('梓椰', 'ziye@example.com', 'dummy_hash_for_ziye', 'moetran_102', FALSE, 64, NULL, now(), NULL),
('sein', 'sein@example.com', 'dummy_hash_for_sein', 'moetran_103', FALSE, 64, NULL, now(), NULL),
('团', 'tuan@example.com', 'dummy_hash_for_tuan', 'moetran_104', FALSE, 64, NULL, now(), NULL),
('文字', 'wenzi@example.com', 'dummy_hash_for_wenzi', 'moetran_105', FALSE, 64, 'N1', now(), NULL),
('2M', '2m@example.com', 'dummy_hash_for_2m', 'moetran_106', FALSE, 64, 'mignon', now(), NULL),
('Mrsk.γ01', 'mrsk.gamma01@example.com', 'dummy_hash_for_mrsk.gamma01', 'moetran_107', FALSE, 64, NULL, now(), NULL),
('兰陵w', 'lanlingw@example.com', 'dummy_hash_for_lanlingw', 'moetran_108', FALSE, 64, NULL, now(), NULL),
('驴驴子', 'lvlvzi@example.com', 'dummy_hash_for_lvlvzi', 'moetran_109', FALSE, 64, NULL, now(), NULL),
('合法', 'hefa@example.com', 'dummy_hash_for_hefa', 'moetran_110', FALSE, 64, NULL, now(), NULL),
('Citrus', 'citrus@example.com', 'dummy_hash_for_citrus', 'moetran_111', FALSE, 64, NULL, now(), NULL),
('JackerJack', 'jackerjack@example.com', 'dummy_hash_for_jackerjack', 'moetran_112', FALSE, 64, NULL, now(), NULL),
('遁音饗塵', 'dunyinxiangchen@example.com', 'dummy_hash_for_dunyinxiangchen', 'moetran_113', FALSE, 64, '原,神,启,动,', now(), NULL),
('上勾拳', 'shanggouquan@example.com', 'dummy_hash_for_shanggouquan', 'moetran_114', FALSE, 64, NULL, now(), NULL),
('待氧化碳/sqz123', 'daiyanghuatan_sqz123@example.com', 'dummy_hash_for_daiyanghuatan_sqz123', 'moetran_115', FALSE, 64, NULL, now(), NULL),
('一体机 想睡觉', 'yitijixiangshuijiao@example.com', 'dummy_hash_for_yitijixiangshuijiao', 'moetran_116', FALSE, 64, '萝莉魅魔', now(), NULL),
('拟态虫', 'nitaihong@example.com', 'dummy_hash_for_nitaihong', 'moetran_117', FALSE, 64, 'mignon', now(), NULL),
('Kin', 'kin@example.com', 'dummy_hash_for_kin', 'moetran_118', FALSE, 128, '（功成身退）, 可以独立接本', now(), NULL),
('Digico', 'digico@example.com', 'dummy_hash_for_digico', 'moetran_119', FALSE, 128, '6.1', now(), NULL),
('蜥蜴', 'lixi@example.com', 'dummy_hash_for_lixi', 'moetran_120', FALSE, 128, '5.1', now(), NULL),
('星尘王大炮', 'xingchenwangdapao@example.com', 'dummy_hash_for_xingchenwangdapao', 'moetran_121', FALSE, 128, '1.3', now(), NULL),
('阿里乌斯小队的狗', 'aliwusixiaoduidagou@example.com', 'dummy_hash_for_aliwusixiaoduidagou', 'moetran_122', FALSE, 128, '1.3', now(), NULL),
('未默', 'weimo@example.com', 'dummy_hash_for_weimo', 'moetran_123', FALSE, 128, '1.3', now(), NULL),
('Soy', 'soy@example.com', 'dummy_hash_for_soy', 'moetran_124', FALSE, 128, '1.30 外', now(), NULL),
('YUU', 'yuu@example.com', 'dummy_hash_for_yuu', 'moetran_125', FALSE, 128, '1.13 外', now(), NULL),
('宫内千华（棕榈的爱犬）', 'gongneiqianhuazonglvdaiaiquan@example.com', 'dummy_hash_for_gongneiqianhuazonglvdaiaiquan', 'moetran_126', FALSE, 128, '1.13', now(), NULL),
('希腊奶', 'xilanai@example.com', 'dummy_hash_for_xilanai', 'moetran_127', FALSE, 128, '7.11', now(), NULL),
('白硝', 'baixiao@example.com', 'dummy_hash_for_baixiao', 'moetran_128', FALSE, 128, '1.13', now(), NULL),
('苏打恋', 'sudalian@example.com', 'dummy_hash_for_sudalian', 'moetran_129', FALSE, 128, '1.13 未来能接（4.25更新）', now(), NULL),
('NoneWhite', 'nonewhite@example.com', 'dummy_hash_for_nonewhite', 'moetran_130', FALSE, 128, '1.13', now(), NULL),
('always be line', 'alwaysbeline@example.com', 'dummy_hash_for_alwaysbeline', 'moetran_131', FALSE, 128, '9.13', now(), NULL),
('阿比魚', 'abiyu@example.com', 'dummy_hash_for_abiyu', 'moetran_132', FALSE, 128, '1.13', now(), NULL),
('春秋分', 'chunqiufen@example.com', 'dummy_hash_for_chunqiufen', 'moetran_133', FALSE, 128, '1.13', now(), NULL),
('L', 'l@example.com', 'dummy_hash_for_l', 'moetran_134', FALSE, 128, '1.13', now(), NULL),
('画画中的小狐狸', 'huahuazhongdexiaohuli@example.com', 'dummy_hash_for_huahuazhongdexiaohuli', 'moetran_135', FALSE, 128, '1.13', now(), NULL),
('竹鼠（猫猫头）', 'zhushumaomaotou@example.com', 'dummy_hash_for_zhushumaomaotou', 'moetran_136', FALSE, 128, '1.13 忙/存活', now(), NULL),
('冰可乐', 'binkele@example.com', 'dummy_hash_for_binkele', 'moetran_137', FALSE, 128, '1.13 忙/存活', now(), NULL),
('小然提不起劲', 'xiaorantipubuqijin@example.com', 'dummy_hash_for_xiaorantipubuqijin', 'moetran_138', FALSE, 128, '1.13', now(), NULL),
('迪奥的黄金呆毛', 'diaodehuangjindaimao@example.com', 'dummy_hash_for_diaodehuangjindaimao', 'moetran_139', FALSE, 128, '1.13', now(), NULL),
('穹呐穹呐穹', 'qiongnahqiongnahqiong@example.com', 'dummy_hash_for_qiongnahqiongnahqiong', 'moetran_140', FALSE, 128, '1.13', now(), NULL),
('沫洛会', 'moluohui@example.com', 'dummy_hash_for_moluohui', 'moetran_141', FALSE, 128, '1.13', now(), NULL),
('ayana', 'ayana@example.com', 'dummy_hash_for_ayana', 'moetran_142', FALSE, 128, '1.13', now(), NULL),
('弱鸡MANAKA', 'ruojimanaka@example.com', 'dummy_hash_for_ruojimanaka', 'moetran_143', FALSE, 128, '1.13', now(), NULL),
('夏目暦', 'xiamulv@example.com', 'dummy_hash_for_xiamulv', 'moetran_144', FALSE, 128, '1.13', now(), NULL),
('生锈薄荷糖', 'shengxiubuohetang@example.com', 'dummy_hash_for_shengxiubuohetang', 'moetran_145', FALSE, 128, NULL, now(), NULL),
('栗悟飯', 'liguwufan@example.com', 'dummy_hash_for_liguwufan', 'moetran_146', FALSE, 128, '1.13', now(), NULL),
('Joders1', 'joders1@example.com', 'dummy_hash_for_joders1', 'moetran_147', FALSE, 128, '1.13 高级', now(), NULL),
('pkuism', 'pkuism@example.com', 'dummy_hash_for_pkuism', 'moetran_148', FALSE, 128, '--------', now(), NULL),
('楠楠', 'nannan@example.com', 'dummy_hash_for_nannan', 'moetran_149', FALSE, 128, '1.13', now(), NULL),
('不，不行…', 'bubuxing@example.com', 'dummy_hash_for_bubuxing', 'moetran_150', FALSE, 128, '1.13', now(), NULL),
('你好我是', 'nihaowoshi@example.com', 'dummy_hash_for_nihaowoshi', 'moetran_151', FALSE, 128, '1.13', now(), NULL),
('Sucofo', 'sucofo@example.com', 'dummy_hash_for_sucofo', 'moetran_152', FALSE, 128, '--------', now(), NULL),
('rua水月的帽子', 'ruashuiyuedemaozi@example.com', 'dummy_hash_for_ruashuiyuedemaozi', 'moetran_153', FALSE, 128, '3.25', now(), NULL),
('雪', 'xue@example.com', 'dummy_hash_for_xue', 'moetran_154', FALSE, 128, '5.27', now(), NULL),
('Angry Fish', 'angryfish@example.com', 'dummy_hash_for_angryfish', 'moetran_155', FALSE, 128, '6.12', now(), NULL),
('本子川', 'benzichuan@example.com', 'dummy_hash_for_benzichuan', 'moetran_156', FALSE, 128, '7.2', now(), NULL),
('伴除使', 'banchushi@example.com', 'dummy_hash_for_banchushi', 'moetran_157', FALSE, 128, '7.25', now(), NULL),
('十月祈雨', 'shiyueqiyu@example.com', 'dummy_hash_for_shiyueqiyu', 'moetran_158', FALSE, 128, '9.21', now(), NULL),
('僵尸', 'jiangshi@example.com', 'dummy_hash_for_jiangshi', 'moetran_159', FALSE, 128, '10.5 夏目, 夏目标记', now(), NULL),
('catbl.|鸟龙', 'catbl.niaolong@example.com', 'dummy_hash_for_catbl.niaolong', 'moetran_160', FALSE, 128, '6.25栗悟饭, 夏目标记', now(), NULL),
('4920', '4920@example.com', 'dummy_hash_for_4920', 'moetran_161', FALSE, 128, '7.13, 夏目标记', now(), NULL),
('江南小米粥', 'jiangnanxiaomizhou@example.com', 'dummy_hash_for_jiangnanxiaomizhou', 'moetran_162', FALSE, 128, '1.13过来玩', now(), NULL),
('路过的游客（游客）', 'luoguodeyoukeyouke@example.com', 'dummy_hash_for_luoguodeyoukeyouke', 'moetran_163', FALSE, 128, '10.23', now(), NULL),
('kk', 'kk@example.com', 'dummy_hash_for_kk', 'moetran_164', FALSE, 128, '栗悟饭', now(), NULL),
('倒地', 'daodi@example.com', 'dummy_hash_for_daodi', 'moetran_165', FALSE, 128, NULL, now(), NULL),
('沐子', 'muzi@example.com', 'dummy_hash_for_muzi', 'moetran_166', FALSE, 128, '1.13星尘王大炮', now(), NULL),
('带善人', 'daishanren@example.com', 'dummy_hash_for_daishanren', 'moetran_167', FALSE, 128, '1.13栗悟饭', now(), NULL),
('秋叶声生', 'qiuyeshengsheng@example.com', 'dummy_hash_for_qiuyeshengsheng', 'moetran_168', FALSE, 128, '7.30夏目, 生病中', now(), NULL),
('祥瑞', 'xiangrui@example.com', 'dummy_hash_for_xiangrui', 'moetran_169', FALSE, 128, '7.30夏目', now(), NULL),
('承栞邯', 'chengkanhan@example.com', 'dummy_hash_for_chengkanhan', 'moetran_170', FALSE, 128, '7.20夏目, 质量欠佳', now(), NULL),
('我永远喜欢砂糖酱', 'woyongyuanxihuanshatangjiang@example.com', 'dummy_hash_for_woyongyuanxihuanshatangjiang', 'moetran_171', FALSE, 128, '1.13夏目, 2.24, 第一本', now(), NULL),
('makabaka', 'makabaka@example.com', 'dummy_hash_for_makabaka', 'moetran_172', FALSE, 128, '1.13/很长时间没有', now(), NULL),
('chuang', 'chuang@example.com', 'dummy_hash_for_chuang', 'moetran_173', FALSE, 128, '2024.6.8之前不能干活', now(), NULL),
('听装可乐', 'tingzhuangkele@example.com', 'dummy_hash_for_tingzhuangkele', 'moetran_174', FALSE, 128, '2.13丸玖', now(), NULL),
('逆转右鹭', 'nizhuanluyu@example.com', 'dummy_hash_for_nizhuanluyu', 'moetran_175', FALSE, 128, '2.15栗悟饭, 夏目标记', now(), NULL),
('啊满', 'aman@example.com', 'dummy_hash_for_aman', 'moetran_176', FALSE, 128, '1.30pk酱', now(), NULL),
('一卷胶带', 'yijuanjiaodai@example.com', 'dummy_hash_for_yijuanjiaodai', 'moetran_177', FALSE, 128, '2.2', now(), NULL),
('mmsuper', 'mmsuper@example.com', 'dummy_hash_for_mmsuper', 'moetran_178', FALSE, 128, '3.21夏目, 16号第一本', now(), NULL),
('隐士', 'yingshi@example.com', 'dummy_hash_for_yingshi', 'moetran_179', FALSE, 128, '08 26 夏目, 第一本, 1月启动', now(), NULL),
('骨白鸽', 'gubaige@example.com', 'dummy_hash_for_gubaige', 'moetran_180', FALSE, 128, '9.13 丸玖, 考研中', now(), NULL),
('奶糖', 'naitang@example.com', 'dummy_hash_for_naitang', 'moetran_181', FALSE, 128, '4.9丸玖, 查无此人', now(), NULL),
('西方', 'xifang@example.com', 'dummy_hash_for_xifang', 'moetran_182', FALSE, 128, '3.16, 栗悟饭, 夏目标记', now(), NULL),
('小春可爱捏', 'xiaochunkeainie@example.com', 'dummy_hash_for_xiaochunkeainie', 'moetran_183', FALSE, 128, '10.17实习中', now(), NULL),
('冥川', 'mingchuan@example.com', 'dummy_hash_for_mingchuan', 'moetran_184', FALSE, 128, '3.21, 4.17之后有空', now(), NULL),
('晓遥', 'xiaoyao@example.com', 'dummy_hash_for_xiaoyao', 'moetran_185', FALSE, 128, '6.8栗悟饭', now(), NULL),
('郭碗瓢盆', 'guowanpiaopen@example.com', 'dummy_hash_for_guowanpiaopen', 'moetran_186', FALSE, 128, NULL, now(), NULL),
('泡泡茶壶', 'paopaochahu@example.com', 'dummy_hash_for_paopaochahu', 'moetran_187', FALSE, 128, '6.17栗悟饭', now(), NULL),
('洛辰', 'luochen@example.com', 'dummy_hash_for_luochen', 'moetran_188', FALSE, 128, '6.25栗悟饭', now(), NULL),
('佳名', 'jiaming@example.com', 'dummy_hash_for_jiaming', 'moetran_189', FALSE, 128, '栗悟饭', now(), NULL),
('祭缘圆寂了', 'jiyuanjuanjile@example.com', 'dummy_hash_for_jiyuanjuanjile', 'moetran_190', FALSE, 128, '栗悟饭', now(), NULL),
('番茄土豆派', 'fanqietudoupie@example.com', 'dummy_hash_for_fanqietudoupie', 'moetran_191', FALSE, 128, '7.18', now(), NULL),
('will', 'will@example.com', 'dummy_hash_for_will', 'moetran_192', FALSE, 128, '9.5栗悟饭', now(), NULL),
('白滴凯鸽', 'baidikaige@example.com', 'dummy_hash_for_baidikaige', 'moetran_193', FALSE, 128, '栗悟饭', now(), NULL),
('gnaygnadi', 'gnaygnadi@example.com', 'dummy_hash_for_gnaygnadi', 'moetran_194', FALSE, 128, NULL, now(), NULL),
('灯灯', 'dengdeng@example.com', 'dummy_hash_for_dengdeng', 'moetran_195', FALSE, 128, NULL, now(), NULL),
('钠钠', 'nana@example.com', 'dummy_hash_for_nana', 'moetran_196', FALSE, 128, 'N3栗悟饭', now(), NULL),
('木板', 'muban@example.com', 'dummy_hash_for_muban', 'moetran_197', FALSE, 128, NULL, now(), NULL),
('Kasumi', 'kasumi@example.com', 'dummy_hash_for_kasumi', 'moetran_198', FALSE, 128, NULL, now(), NULL),
('tbm1233', 'tbm1233@example.com', 'dummy_hash_for_tbm1233', 'moetran_199', FALSE, 128, NULL, now(), NULL),
('空白blank', 'kongbaiblank@example.com', 'dummy_hash_for_kongbaiblank', 'moetran_200', FALSE, 128, '9.26 夏目', now(), NULL),
('焱铃', 'yanling@example.com', 'dummy_hash_for_yanling', 'moetran_201', FALSE, 128, '9.28 夏目', now(), NULL),
('mirage', 'mirage@example.com', 'dummy_hash_for_mirage', 'moetran_202', FALSE, 128, '11.4栗悟饭', now(), NULL),
('科林斯', 'kelinsi@example.com', 'dummy_hash_for_kelinsi', 'moetran_203', FALSE, 128, '11.8栗悟饭', now(), NULL),
('风华正喵QAQ', 'fenghuazhengmiaoqaq@example.com', 'dummy_hash_for_fenghuazhengmiaoqaq', 'moetran_204', FALSE, 128, NULL, now(), NULL),
('渚清少婉', 'zhuqingshaowan@example.com', 'dummy_hash_for_zhuqingshaowan', 'moetran_205', FALSE, 128, NULL, now(), NULL),
('花_宇_', 'hua_yu_@example.com', 'dummy_hash_for_hua_yu_', 'moetran_206', FALSE, 128, NULL, now(), NULL),
('Dexa', 'dexa@example.com', 'dummy_hash_for_dexa', 'moetran_207', FALSE, 128, NULL, now(), NULL),
('塔塔', 'tata@example.com', 'dummy_hash_for_tata', 'moetran_208', FALSE, 128, NULL, now(), NULL),
('东方东方', 'dongfangdongfang@example.com', 'dummy_hash_for_dongfangdongfang', 'moetran_209', FALSE, 128, '栗悟饭', now(), NULL),
('bin', 'bin@example.com', 'dummy_hash_for_bin', 'moetran_210', FALSE, 128, NULL, now(), NULL),
('yimeko', 'yimeko@example.com', 'dummy_hash_for_yimeko', 'moetran_211', FALSE, 128, NULL, now(), NULL),
('豆泡影', 'doupaoying@example.com', 'dummy_hash_for_doupaoying', 'moetran_212', FALSE, 128, '栗悟饭', now(), NULL),
('SD無', 'sdwu@example.com', 'dummy_hash_for_sdwu', 'moetran_213', FALSE, 128, NULL, now(), NULL),
('绳系', 'shengxi@example.com', 'dummy_hash_for_shengxi', 'moetran_214', FALSE, 128, NULL, now(), NULL),
('狂嗦美游脚', 'kuangsuomeiyoujiao@example.com', 'dummy_hash_for_kuangsuomeiyoujiao', 'moetran_215', FALSE, 128, NULL, now(), NULL),
('迟雨', 'chiyu@example.com', 'dummy_hash_for_chiyu', 'moetran_216', FALSE, 128, '夏目', now(), NULL),
('兰棠', 'lantang@example.com', 'dummy_hash_for_lantang', 'moetran_217', FALSE, 128, NULL, now(), NULL),
('C.dissenminatus 白小鬼', 'c.dissenminatusbaixiaogui@example.com', 'dummy_hash_for_c.dissenminatusbaixiaogui', 'moetran_218', FALSE, 128, '栗悟饭', now(), NULL),
('辉夜', 'huiye@example.com', 'dummy_hash_for_huiye', 'moetran_219', FALSE, 32, '英翻', now(), NULL),
('Tong', 'tong@example.com', 'dummy_hash_for_tong', 'moetran_220', FALSE, 32, '英翻', now(), NULL);
