package dbmodels

import "unsafe"

// 为 GORM 自带的 uint 主键类型起一个醒目的别名
type PrimaryKey uint

// 职责掩码位移
const (
	LABOR_CREATOR_SHIFT = iota
	LABOR_PRICINPAL_SHIFT
	LABOR_SRC_PROV_SHIFT
	LABOR_CLEANER_SHIFT
	LABOR_GRAPHIC_PROC_SHIFT
	LABOR_TRANSLATOR_SHIFT
	LABOR_PROOF_SHIFT
	LABOR_LETTERER_SHIFT
	LABOR_REVIEWER_SHIFT
)

// 项目状态掩码
// 对应位是1代表正在处于该状态
const (
	// 当前项目 status 如果为 0 是未定义的
	PROJ_STATUS_UNSET_MASK = 1 << iota
	PROJ_STATUS_ON_TRANSLATING_MASK
	PROJ_STATUS_TRANSLATED_MASK
	PROJ_STATUS_ON_PROOF_MASK
	PROJ_STATUS_PROVED_MASK
	PROJ_STATUS_ON_LETTERING_MASK
	PROJ_STATUS_LETTERED_MASK
	PROJ_STATUS_ON_REVIEWING_MASK
	PROJ_STATUS_REVIEWED_MASK
	PROJ_STATUS_PUBLISHED_MASK

	// 这里所取的是最高位，可以直接检查
	PROJ_STATUS_CANCELED = 1 << (unsafe.Sizeof(Project{}.Status)*8 - 1)
)
