// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/project/labor/accept": {
            "post": {
                "description": "接受邀请加入项目，需提供邀请的 ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "接受邀请加入项目",
                "parameters": [
                    {
                        "description": "接受邀请加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AcceptInvitationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/labor/accept_appli": {
            "post": {
                "description": "接受申请加入项目，需提供申请的 ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "接受申请加入项目",
                "parameters": [
                    {
                        "description": "接受申请加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.AcceptApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/labor/apply": {
            "post": {
                "description": "申请加入项目，需提供项目 ID 和申请的职位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "申请加入项目",
                "parameters": [
                    {
                        "description": "申请加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ApplyProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/labor/division": {
            "get": {
                "description": "获取指定项目的分工信息，包括成员的角色和状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "获取指定项目的分工信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID，必填",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.LaborDivision"
                            }
                        }
                    }
                }
            }
        },
        "/project/labor/invite": {
            "post": {
                "description": "邀请成员加入项目，需提供成员的 ID、项目 ID 和邀请职位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "邀请成员加入项目",
                "parameters": [
                    {
                        "description": "邀请成员加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.InviteMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/labor/refuse": {
            "post": {
                "description": "拒绝邀请加入项目，需提供邀请的 ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "拒绝邀请加入项目",
                "parameters": [
                    {
                        "description": "拒绝邀请加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RefuseInvitationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/labor/refuse_appli": {
            "post": {
                "description": "拒绝申请加入项目，需提供申请的 ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "拒绝申请加入项目",
                "parameters": [
                    {
                        "description": "拒绝申请加入项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.RefuseApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project/list": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组；如果要单独查询已发布的项目列表，请使用 /project/published_list 接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "获取项目列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "排序方式，0：按 ID 倒序，1：按 updated_at 倒序",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目状态（位掩码），用于复合查询，默认不筛选查询",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目所属的作品集 ID，必填",
                        "name": "workset_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProjectBasic"
                            }
                        }
                    }
                }
            }
        },
        "/project/proc/create": {
            "post": {
                "description": "创建一个新的项目，请求体暂时未确定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "description": "创建项目的请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/project/proc/delete": {
            "delete": {
                "description": "删除指定的项目，需提供项目 ID",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "description": "要删除项目的信息",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.DeleteProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/proc/update_info": {
            "put": {
                "description": "更新指定的项目，需提供项目 ID",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "更新项目",
                "parameters": [
                    {
                        "description": "更新的项目信息",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/proc/update_status": {
            "put": {
                "description": "更新指定项目的状态，需提供项目 ID 和新的状态，调用一次只允许更新一个状态",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "更新项目状态",
                "parameters": [
                    {
                        "description": "更新项目状态的信息",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateProjectStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/{id}": {
            "get": {
                "description": "获取指定项目的详细信息，包括翻译、校对、嵌字、审核、发布等状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "获取项目详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProjectDetail"
                        }
                    }
                }
            }
        },
        "/team/member_list": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "获取汉化组成员列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "所属汉化组 ID，必填",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.MemberBasic"
                            }
                        }
                    }
                }
            }
        },
        "/user/detail": {
            "get": {
                "description": "获取指定用户的详细信息，包括 ID、用户名、头像等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserDetail"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方式，默认值为 id_desc，支持 id_asc | id_desc，其他输入无效",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.UserBasic"
                            }
                        }
                    }
                }
            }
        },
        "/user/my/detail": {
            "get": {
                "description": "获取当前登录用户的详细信息，包括 ID、用户名、头像等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_my"
                ],
                "summary": "获取当前用户的详细信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserDetail"
                        }
                    }
                }
            }
        },
        "/user/my/invitations_received": {
            "get": {
                "description": "获取当前登录用户收到的所有邀请列表，仅包括项目邀请",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_my"
                ],
                "summary": "获取当前用户的收到的邀请列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.InvitationBasic"
                            }
                        }
                    }
                }
            }
        },
        "/user/my/invitations_sent": {
            "get": {
                "description": "获取当前登录用户发出的所有邀请列表，仅包括项目邀请",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_my"
                ],
                "summary": "获取当前用户的邀请列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.InvitationBasic"
                            }
                        }
                    }
                }
            }
        },
        "/user/my/projects": {
            "get": {
                "description": "获取当前登录用户参与的所有项目列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_my"
                ],
                "summary": "获取当前用户的项目列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProjectBasic"
                            }
                        }
                    }
                }
            }
        },
        "/user/my/teams": {
            "get": {
                "description": "获取当前登录用户所属的所有汉化组列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user_my"
                ],
                "summary": "获取当前用户的汉化组列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.TeamBasic"
                            }
                        }
                    }
                }
            }
        },
        "/workset/list": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workset"
                ],
                "summary": "获取工作集列表分页，按 ID 倒序",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "所属汉化组 ID",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.WorksetBasic"
                            }
                        }
                    }
                }
            }
        },
        "/workset/stats": {
            "get": {
                "description": "获取所有项目的统计信息，包括总数、翻译、校对、嵌字，审核、发布对应数量等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workset"
                ],
                "summary": "获取特定作品集项目统计信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "作品集 ID，必填",
                        "name": "workset_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProjectStats"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.AcceptApplicationRequest": {
            "type": "object",
            "required": [
                "application_id"
            ],
            "properties": {
                "application_id": {
                    "description": "申请的 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.AcceptInvitationRequest": {
            "type": "object",
            "required": [
                "invitation_id"
            ],
            "properties": {
                "invitation_id": {
                    "description": "邀请的 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.ApplyProjectRequest": {
            "type": "object",
            "required": [
                "apply_role",
                "project_id"
            ],
            "properties": {
                "apply_role": {
                    "description": "申请加入的职位 (使用 uint 存储位掩码)",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.CreateProjectRequest": {
            "type": "object",
            "required": [
                "title",
                "workset_id"
            ],
            "properties": {
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "title": {
                    "description": "项目标题，必填，最大长度 40",
                    "type": "string"
                },
                "workset_id": {
                    "description": "作品集 ID，必填",
                    "type": "integer"
                }
            }
        },
        "dtos.DeleteProjectRequest": {
            "type": "object",
            "required": [
                "project_id"
            ],
            "properties": {
                "project_id": {
                    "description": "项目 ID，必填",
                    "type": "integer"
                }
            }
        },
        "dtos.InvitationBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "邀请 ID",
                    "type": "integer"
                },
                "invite_role": {
                    "description": "邀请的角色，使用位掩码表示",
                    "type": "integer"
                },
                "invitee_id": {
                    "description": "被邀请者 ID",
                    "type": "integer"
                },
                "inviter_id": {
                    "description": "邀请者 ID",
                    "type": "integer"
                },
                "project_id": {
                    "description": "所属项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.InviteMemberRequest": {
            "type": "object",
            "required": [
                "invite_role",
                "member_id",
                "project_id"
            ],
            "properties": {
                "invite_role": {
                    "description": "邀请加入的职位 (使用 uint 存储位掩码)",
                    "type": "integer"
                },
                "member_id": {
                    "description": "成员的 ID",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.LaborDivision": {
            "type": "object",
            "properties": {
                "member_id": {
                    "description": "成员 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "role": {
                    "description": "成员在项目中的角色，使用位掩码表示",
                    "type": "integer"
                }
            }
        },
        "dtos.MemberBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "成员 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "role": {
                    "description": "成员在组内的职责",
                    "type": "integer"
                },
                "team_id": {
                    "description": "所属团队 ID",
                    "type": "integer"
                },
                "user_id": {
                    "description": "实际上的用户 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectBasic": {
            "type": "object",
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入",
                    "type": "boolean"
                },
                "id": {
                    "description": "项目 ID",
                    "type": "integer"
                },
                "is_hidden": {
                    "description": "是否是隐藏项目",
                    "type": "boolean"
                },
                "is_published": {
                    "description": "是否已发布",
                    "type": "boolean"
                },
                "legacy_id": {
                    "description": "历史遗留序号",
                    "type": "integer"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "title": {
                    "description": "项目名称",
                    "type": "string"
                },
                "workset_id": {
                    "description": "所属作品集 ID",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectDetail": {
            "type": "object",
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入",
                    "type": "boolean"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "id": {
                    "description": "项目 ID",
                    "type": "integer"
                },
                "is_hidden": {
                    "description": "是否是隐藏项目",
                    "type": "boolean"
                },
                "is_published": {
                    "description": "是否已发布",
                    "type": "boolean"
                },
                "legacy_id": {
                    "description": "历史遗留序号",
                    "type": "integer"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "title": {
                    "description": "项目名称",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "workset_id": {
                    "description": "所属作品集 ID",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectOverallStatus": {
            "type": "integer",
            "enum": [
                3,
                12,
                48,
                192,
                768
            ],
            "x-enum-comments": {
                "PROJECT_STATUS_LETTER_MASK": "二进制 48",
                "PROJECT_STATUS_PROOF_MASK": "二进制 12",
                "PROJECT_STATUS_PUBLISH_MASK": "二进制 768",
                "PROJECT_STATUS_REVIEW_MASK": "二进制 192",
                "PROJECT_STATUS_TRANSLATE_MASK": "二进制 3"
            },
            "x-enum-varnames": [
                "PROJECT_STATUS_TRANSLATE_MASK",
                "PROJECT_STATUS_PROOF_MASK",
                "PROJECT_STATUS_LETTER_MASK",
                "PROJECT_STATUS_REVIEW_MASK",
                "PROJECT_STATUS_PUBLISH_MASK"
            ]
        },
        "dtos.ProjectStats": {
            "type": "object",
            "properties": {
                "lettered_count": {
                    "description": "已嵌字的项目数量",
                    "type": "integer"
                },
                "lettering_count": {
                    "description": "正在嵌字的项目数量",
                    "type": "integer"
                },
                "not_lettering_count": {
                    "description": "未开始嵌字的项目数量",
                    "type": "integer"
                },
                "not_prooving_count": {
                    "description": "未开始校对的项目数量",
                    "type": "integer"
                },
                "not_reviewing_count": {
                    "description": "未开始审核的项目数量",
                    "type": "integer"
                },
                "not_translating_count": {
                    "description": "未开始翻译的项目数量",
                    "type": "integer"
                },
                "prooved_count": {
                    "description": "已校对的项目数量",
                    "type": "integer"
                },
                "prooving_count": {
                    "description": "正在校对的项目数量",
                    "type": "integer"
                },
                "published_count": {
                    "description": "已发布项目数量",
                    "type": "integer"
                },
                "reviewed_count": {
                    "description": "已审核的项目数量",
                    "type": "integer"
                },
                "reviewing_count": {
                    "description": "正在审核的项目数量",
                    "type": "integer"
                },
                "total_count": {
                    "description": "总项目数量",
                    "type": "integer"
                },
                "translated_count": {
                    "description": "已翻译的项目数量",
                    "type": "integer"
                },
                "translating_count": {
                    "description": "正在翻译的项目数量",
                    "type": "integer"
                },
                "workset_id": {
                    "description": "对应作品集 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.RefuseApplicationRequest": {
            "type": "object",
            "required": [
                "application_id"
            ],
            "properties": {
                "application_id": {
                    "description": "申请的 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.RefuseInvitationRequest": {
            "type": "object",
            "required": [
                "invitation_id"
            ],
            "properties": {
                "invitation_id": {
                    "description": "邀请的 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.TeamBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "团队 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "团队名称",
                    "type": "string"
                }
            }
        },
        "dtos.UpdateProjectRequest": {
            "type": "object",
            "required": [
                "project_id",
                "title"
            ],
            "properties": {
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目 ID，必填",
                    "type": "integer"
                },
                "title": {
                    "description": "项目标题，最大长度 40",
                    "type": "string"
                }
            }
        },
        "dtos.UpdateProjectStatusRequest": {
            "type": "object",
            "required": [
                "project_id",
                "status"
            ],
            "properties": {
                "project_id": {
                    "description": "项目 ID，必填",
                    "type": "integer"
                },
                "status": {
                    "description": "新的项目状态，必填",
                    "type": "integer"
                }
            }
        },
        "dtos.UserBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                }
            }
        },
        "dtos.UserDetail": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "用户 ID",
                    "type": "integer"
                },
                "last_active": {
                    "description": "上次活跃时间",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "poplar_is_admin": {
                    "description": "是否是 panel 管理员",
                    "type": "boolean"
                },
                "qq_number": {
                    "description": "QQ 号",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                }
            }
        },
        "dtos.WorksetBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "作品集 ID",
                    "type": "integer"
                },
                "moetran_id": {
                    "description": "Moetran ID",
                    "type": "string"
                },
                "name": {
                    "description": "作品集名称",
                    "type": "string"
                },
                "team_id": {
                    "description": "所属团队 ID",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PoplarGrid 核心 API 服务器",
	Description:      "PoplarGrid API 服务器，提供项目、成员等操作功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
