// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "description": "根据分页参数获取用户的申请列表，支持分页和排序。当列表为空",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "获取当前用户的申请（发出或收到）列表，支持分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "申请类型，0：发出的申请，1：收到的申请",
                        "name": "kind",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ApplicationBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的申请，申请加入项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "创建一个新的申请",
                "parameters": [
                    {
                        "description": "申请参数",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ApplyProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "申请创建成功",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/invitations": {
            "get": {
                "description": "根据分页参数获取用户的邀请列表，支持分页和排序。当列表为空时，会返回 null 而不是空数组。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "获取当前用户的邀请（发出或者收到）列表，支持分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "邀请类型，0：发送的邀请，1：收到的邀请",
                        "name": "kind",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.InvitationBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的邀请，邀请用户加入项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "创建一个新的邀请",
                "parameters": [
                    {
                        "description": "邀请参数",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.InviteMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "邀请创建成功",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "根据作品集 ID 获取项目列表，支持分页、排序和状态筛选。当列表为空时，会返回 null 而不是空数组。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "获取项目列表分页 (按作品集筛选)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "排序方式，0：按 ID 倒序，1：按 updated_at 倒序",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目状态（位掩码），用于复合查询，默认不筛选查询",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户 ID，默认不筛选用户",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目所属的作品集 ID，默认不筛选作品集",
                        "name": "workset_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProjectBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "创建项目",
                "parameters": [
                    {
                        "description": "创建项目的请求体",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProjectCreatedInfo"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "description": "获取指定项目的详细信息，包括翻译、校对、嵌字、审核、发布等状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "获取项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProjectDetail"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的项目，需提供项目 ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "更新指定的项目，需提供项目 ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_proc"
                ],
                "summary": "更新项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的项目信息",
                        "name": "body_params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}/labors": {
            "get": {
                "description": "获取指定项目的分工信息，包括成员的角色和状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project_labor"
                ],
                "summary": "获取指定项目的分工信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.LaborDivision"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "根据分页参数获取汉化组列表，支持分页和排序。当列表为空时，会返回 null 而不是空数组。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "获取当前用户的汉化组列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.TeamBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams/{id}/members": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "获取汉化组成员列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "要模糊搜索的成员（部分）昵称",
                        "name": "member_nickname",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "要搜索的成员的 QQ 号，使用 interger 加速查找",
                        "name": "member_qq",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "所属汉化组 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.MemberBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/applications": {
            "get": {
                "description": "根据分页参数获取用户的申请列表，支持分页和排序\\n当列表为空时，会返回 null 而不是空数组\\n如果 id 不是当前登录的用户 ID，则返回 400 错误",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "获取当前用户的申请（发出或收到）列表，支持分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "申请类型，0：发送的申请，1：收到的申请",
                        "name": "kind",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ApplicationBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/detail": {
            "get": {
                "description": "获取指定用户的详细信息，包括 ID、昵称、QQ 等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserDetail"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/invitations": {
            "get": {
                "description": "根据分页参数获取用户的邀请列表，支持分页和排序\\n当列表为空时，会返回 null 而不是空数组\\n如果 id 不是当前登录的用户 ID，则返回 400 错误",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invitation"
                ],
                "summary": "获取当前用户的邀请（发出或者收到）列表，支持分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邀请类型，0：发送的邀请，1：收到的邀请",
                        "name": "kind",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.InvitationBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/projects": {
            "get": {
                "description": "获取指定用户参与的所有项目列表，支持分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取用户参与的项目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.MyProjectBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/teams": {
            "get": {
                "description": "获取指定用户参与的所有汉化组列表，支持分页和排序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前用户参与的汉化组列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.TeamBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/worksets": {
            "get": {
                "description": "注意当列表为空，会返回 null 而不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workset"
                ],
                "summary": "获取特定汉化组的工作集列表分页，按 ID 倒序",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "page_serial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "所属汉化组 ID",
                        "name": "team_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.WorksetBasic"
                            }
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/worksets/{id}/stats": {
            "get": {
                "description": "获取所有项目的统计信息，包括总数、翻译、校对、嵌字，审核、发布对应数量等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workset"
                ],
                "summary": "获取特定作品集项目统计信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "作品集 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProjectStats"
                        }
                    },
                    "400": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ApplicationBasic": {
            "type": "object",
            "properties": {
                "applicant_id": {
                    "description": "申请者 ID",
                    "type": "integer"
                },
                "id": {
                    "description": "申请 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "申请者昵称",
                    "type": "string"
                },
                "project": {
                    "description": "所属项目的基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.InnerProject"
                        }
                    ]
                },
                "role": {
                    "description": "申请的角色，使用位掩码表示",
                    "type": "integer"
                },
                "status": {
                    "description": "申请状态，0 pending, 1 accepted, 2 rejected",
                    "type": "integer"
                }
            }
        },
        "dtos.ApplyProjectRequest": {
            "type": "object",
            "required": [
                "apply_role",
                "project_id"
            ],
            "properties": {
                "apply_role": {
                    "description": "申请加入的职位 (使用 uint 存储位掩码)",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.CreateProjectRequest": {
            "type": "object",
            "required": [
                "title",
                "workset_id"
            ],
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入，默认为 false",
                    "type": "boolean"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "is_hidden": {
                    "description": "是否隐藏项目，默认为 false",
                    "type": "boolean"
                },
                "title": {
                    "description": "项目标题，必填",
                    "type": "string"
                },
                "workset_id": {
                    "description": "作品集 ID，必填",
                    "type": "integer"
                }
            }
        },
        "dtos.InnerProject": {
            "type": "object",
            "properties": {
                "project_id": {
                    "description": "所属项目 ID",
                    "type": "integer"
                },
                "project_title": {
                    "description": "项目标题",
                    "type": "string"
                },
                "status": {
                    "description": "项目状态，使用位",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "workset_id": {
                    "description": "所属作品",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.InvitationBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "邀请 ID",
                    "type": "integer"
                },
                "invite_role": {
                    "description": "邀请的角色，使用位掩码表示",
                    "type": "integer"
                },
                "invitee_id": {
                    "description": "InviterNickname string ` + "`" + `json:\"inviter_nickname\"` + "`" + ` // 邀请者昵称",
                    "type": "integer"
                },
                "invitee_nickname": {
                    "description": "被邀请者昵称",
                    "type": "string"
                },
                "inviter_id": {
                    "description": "邀请者 ID",
                    "type": "integer"
                },
                "project": {
                    "description": "所属项目的基本信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.InnerProject"
                        }
                    ]
                },
                "status": {
                    "description": "邀请状态，0 pending, 1 accepted, 2 rejected",
                    "type": "integer"
                }
            }
        },
        "dtos.InviteMemberRequest": {
            "type": "object",
            "required": [
                "invite_role",
                "member_id",
                "project_id"
            ],
            "properties": {
                "invite_role": {
                    "description": "邀请加入的职位 (使用 uint 存储位掩码)",
                    "type": "integer"
                },
                "member_id": {
                    "description": "成员的 ID",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.LaborDivision": {
            "type": "object",
            "properties": {
                "member_id": {
                    "description": "成员 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "role": {
                    "description": "成员在项目中的角色，使用位掩码表示",
                    "type": "integer"
                }
            }
        },
        "dtos.MemberBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "成员 ID",
                    "type": "integer"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "role": {
                    "description": "成员在组内的职责",
                    "type": "integer"
                },
                "team_id": {
                    "description": "所属团队 ID",
                    "type": "integer"
                },
                "user_id": {
                    "description": "实际上的用户 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.MyProjectBasic": {
            "type": "object",
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入",
                    "type": "boolean"
                },
                "id": {
                    "description": "项目 ID",
                    "type": "integer"
                },
                "is_hidden": {
                    "description": "是否是隐藏项目",
                    "type": "boolean"
                },
                "is_published": {
                    "description": "是否已发布",
                    "type": "boolean"
                },
                "joined_time": {
                    "description": "加入的时间",
                    "type": "string"
                },
                "legacy_id": {
                    "description": "历史遗留序号",
                    "type": "integer"
                },
                "moetran_id": {
                    "description": "龙译 ID",
                    "type": "string"
                },
                "principal_id": {
                    "description": "项目的负责人 ID",
                    "type": "integer"
                },
                "role": {
                    "description": "成员在项目中的角色，使用掩码计算多重身份",
                    "type": "integer"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "title": {
                    "description": "项目名称",
                    "type": "string"
                },
                "workset_id": {
                    "description": "所属作品集 ID",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectBasic": {
            "type": "object",
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入",
                    "type": "boolean"
                },
                "id": {
                    "description": "项目 ID",
                    "type": "integer"
                },
                "is_hidden": {
                    "description": "是否是隐藏项目",
                    "type": "boolean"
                },
                "is_published": {
                    "description": "是否已发布",
                    "type": "boolean"
                },
                "legacy_id": {
                    "description": "历史遗留序号",
                    "type": "integer"
                },
                "moetran_id": {
                    "description": "龙译 ID",
                    "type": "string"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "title": {
                    "description": "项目名称",
                    "type": "string"
                },
                "workset_id": {
                    "description": "所属作品集 ID",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectCreatedInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "响应消息",
                    "type": "string"
                },
                "moetran_id": {
                    "description": "龙译项目 ID",
                    "type": "string"
                },
                "project_id": {
                    "description": "创建的项目 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectDetail": {
            "type": "object",
            "properties": {
                "allow_auto_join": {
                    "description": "是否允许自动加入",
                    "type": "boolean"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "id": {
                    "description": "项目 ID",
                    "type": "integer"
                },
                "is_hidden": {
                    "description": "是否是隐藏项目",
                    "type": "boolean"
                },
                "is_published": {
                    "description": "是否已发布",
                    "type": "boolean"
                },
                "legacy_id": {
                    "description": "历史遗留序号",
                    "type": "integer"
                },
                "moetran_id": {
                    "description": "龙译 ID",
                    "type": "string"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProjectOverallStatus"
                        }
                    ]
                },
                "title": {
                    "description": "项目名称",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "workset_id": {
                    "description": "所属作品集 ID",
                    "type": "integer"
                },
                "workset_index": {
                    "description": "作品集内的序号",
                    "type": "integer"
                }
            }
        },
        "dtos.ProjectOverallStatus": {
            "type": "integer",
            "enum": [
                3,
                12,
                48,
                192,
                768
            ],
            "x-enum-comments": {
                "PROJECT_STATUS_LETTER_MASK": "二进制 48",
                "PROJECT_STATUS_PROOF_MASK": "二进制 12",
                "PROJECT_STATUS_PUBLISH_MASK": "二进制 768",
                "PROJECT_STATUS_REVIEW_MASK": "二进制 192",
                "PROJECT_STATUS_TRANSLATE_MASK": "二进制 3"
            },
            "x-enum-varnames": [
                "PROJECT_STATUS_TRANSLATE_MASK",
                "PROJECT_STATUS_PROOF_MASK",
                "PROJECT_STATUS_LETTER_MASK",
                "PROJECT_STATUS_REVIEW_MASK",
                "PROJECT_STATUS_PUBLISH_MASK"
            ]
        },
        "dtos.ProjectStats": {
            "type": "object",
            "properties": {
                "lettered_count": {
                    "description": "已嵌字的项目数量",
                    "type": "integer"
                },
                "lettering_count": {
                    "description": "正在嵌字的项目数量",
                    "type": "integer"
                },
                "not_lettering_count": {
                    "description": "未开始嵌字的项目数量",
                    "type": "integer"
                },
                "not_prooving_count": {
                    "description": "未开始校对的项目数量",
                    "type": "integer"
                },
                "not_reviewing_count": {
                    "description": "未开始审核的项目数量",
                    "type": "integer"
                },
                "not_translating_count": {
                    "description": "未开始翻译的项目数量",
                    "type": "integer"
                },
                "prooved_count": {
                    "description": "已校对的项目数量",
                    "type": "integer"
                },
                "prooving_count": {
                    "description": "正在校对的项目数量",
                    "type": "integer"
                },
                "published_count": {
                    "description": "已发布项目数量",
                    "type": "integer"
                },
                "reviewed_count": {
                    "description": "已审核的项目数量",
                    "type": "integer"
                },
                "reviewing_count": {
                    "description": "正在审核的项目数量",
                    "type": "integer"
                },
                "total_count": {
                    "description": "总项目数量",
                    "type": "integer"
                },
                "translated_count": {
                    "description": "已翻译的项目数量",
                    "type": "integer"
                },
                "translating_count": {
                    "description": "正在翻译的项目数量",
                    "type": "integer"
                },
                "workset_id": {
                    "description": "对应作品集 ID",
                    "type": "integer"
                }
            }
        },
        "dtos.TeamBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "团队 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "团队名称",
                    "type": "string"
                }
            }
        },
        "dtos.UpdateProjectRequest": {
            "type": "object",
            "required": [
                "project_id",
                "title"
            ],
            "properties": {
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目 ID，必填",
                    "type": "integer"
                },
                "status": {
                    "description": "项目状态，使用位掩码表示",
                    "type": "integer"
                },
                "title": {
                    "description": "项目标题",
                    "type": "string"
                }
            }
        },
        "dtos.UserDetail": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "用户 ID",
                    "type": "integer"
                },
                "last_active": {
                    "description": "上次活跃时间",
                    "type": "string"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "poplar_is_admin": {
                    "description": "是否是 panel 管理员",
                    "type": "boolean"
                },
                "qq_number": {
                    "description": "QQ 号",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                }
            }
        },
        "dtos.WorksetBasic": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "作品集 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "作品集名称",
                    "type": "string"
                },
                "team_id": {
                    "description": "所属团队 ID",
                    "type": "integer"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "可选，在 service 层发生错误时提供详细信息",
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.SuccessResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "可选，提供额外的成功信息"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PoplarGrid 核心 API 服务器",
	Description:      "PoplarGrid API 服务器，提供项目、成员等操作功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
