// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/member/list": {
            "get": {
                "description": "注意当列表为空，会返回 null 费不是空数组",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "member"
                ],
                "summary": "获取成员详细信息的列表分页，如果想要获取全部内容可以设置一个很大的 pageSize",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "pageSerial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.MemberFullInfo"
                            }
                        }
                    }
                }
            }
        },
        "/proj/list": {
            "get": {
                "description": "注意当列表为空返回值是 null 而非 []",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "project"
                ],
                "summary": "获取项目列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认值为 1",
                        "name": "pageSerial",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认值为 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProjectFullInfo"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.MemberFullInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "labors": {
                    "type": "integer"
                },
                "last_active": {
                    "description": "格式为 \"2006-01-02 15:04:05\"",
                    "type": "string"
                },
                "member_id": {
                    "type": "integer"
                },
                "moetran_id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "poplar_is_admin": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "dtos.ProjectFullInfo": {
            "type": "object",
            "properties": {
                "labor_division": {
                    "description": "分工成员列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ProjectMemberLabor"
                    }
                },
                "legacy_id": {
                    "type": "integer"
                },
                "project_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "team": {
                    "description": "汉化组信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.TeamFullInfo"
                        }
                    ]
                },
                "title": {
                    "type": "string"
                },
                "urgency": {
                    "type": "integer"
                },
                "work": {
                    "description": "作品信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.WorkFullInfo"
                        }
                    ]
                },
                "workset": {
                    "description": "作品集信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.WorksetFullInfo"
                        }
                    ]
                }
            }
        },
        "dtos.ProjectMemberLabor": {
            "type": "object",
            "properties": {
                "labor_role": {
                    "description": "分工角色，使用位掩码存储",
                    "type": "integer"
                },
                "member_name": {
                    "description": "成员昵称",
                    "type": "string"
                }
            }
        },
        "dtos.TeamFullInfo": {
            "type": "object",
            "properties": {
                "moetran_id": {
                    "description": "尨译 ID",
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "dtos.WorkFullInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "moetran_id": {
                    "description": "尨译 ID",
                    "type": "string"
                },
                "tags": {
                    "description": "标签列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "work_id": {
                    "type": "integer"
                }
            }
        },
        "dtos.WorksetFullInfo": {
            "type": "object",
            "properties": {
                "moetran_id": {
                    "description": "尨译 ID",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "workset_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8071",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PoplarGrid API 服务器",
	Description:      "PoplarGrid 服务器的 API 处理服务器，负责协调表格相关业务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
