definitions:
  dtos.AcceptApplicationRequest:
    properties:
      application_id:
        description: 申请的 ID
        type: integer
    required:
    - application_id
    type: object
  dtos.AcceptInvitationRequest:
    properties:
      invitation_id:
        description: 邀请的 ID
        type: integer
    required:
    - invitation_id
    type: object
  dtos.ApplyProjectRequest:
    properties:
      apply_role:
        description: 申请加入的职位 (使用 uint 存储位掩码)
        type: integer
      project_id:
        description: 项目 ID
        type: integer
    required:
    - apply_role
    - project_id
    type: object
  dtos.CreateProjectRequest:
    properties:
      description:
        description: 项目描述
        type: string
      title:
        description: 项目标题，必填，最大长度 40
        type: string
      workset_id:
        description: 作品集 ID，必填
        type: integer
    required:
    - title
    - workset_id
    type: object
  dtos.DeleteProjectRequest:
    properties:
      project_id:
        description: 项目 ID，必填
        type: integer
    required:
    - project_id
    type: object
  dtos.InviteMemberRequest:
    properties:
      invite_role:
        description: 邀请加入的职位 (使用 uint 存储位掩码)
        type: integer
      member_id:
        description: 成员的 ID
        type: integer
      project_id:
        description: 项目 ID
        type: integer
    required:
    - invite_role
    - member_id
    - project_id
    type: object
  dtos.MemberBasic:
    properties:
      id:
        description: 成员 ID
        type: integer
      role:
        description: 成员在组内的职责
        type: integer
      team_id:
        description: 所属团队 ID
        type: integer
    type: object
  dtos.ProjectBasic:
    properties:
      allow_auto_join:
        description: 是否允许自动加入
        type: boolean
      id:
        description: 项目 ID
        type: integer
      is_hidden:
        description: 是否是隐藏项目
        type: boolean
      is_published:
        description: 是否已发布
        type: boolean
      legacy_id:
        description: 历史遗留序号
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/dtos.ProjectOverallStatus'
        description: 项目状态，使用位掩码表示
      title:
        description: 项目名称
        type: string
      workset_id:
        description: 所属作品集 ID
        type: integer
    type: object
  dtos.ProjectDetail:
    properties:
      allow_auto_join:
        description: 是否允许自动加入
        type: boolean
      created_at:
        description: 创建时间
        type: string
      description:
        description: 项目描述
        type: string
      id:
        description: 项目 ID
        type: integer
      is_hidden:
        description: 是否是隐藏项目
        type: boolean
      is_published:
        description: 是否已发布
        type: boolean
      legacy_id:
        description: 历史遗留序号
        type: integer
      moetran_id:
        description: Moetran ID
        type: string
      status:
        allOf:
        - $ref: '#/definitions/dtos.ProjectOverallStatus'
        description: 项目状态，使用位掩码表示
      title:
        description: 项目名称
        type: string
      updated_at:
        description: 更新时间
        type: string
      workset_id:
        description: 所属作品集 ID
        type: integer
    type: object
  dtos.ProjectOverallStatus:
    enum:
    - 3
    - 12
    - 48
    - 192
    type: integer
    x-enum-comments:
      PROJECT_STATUS_LETTER_MASK: 二进制 48
      PROJECT_STATUS_PROOF_MASK: 二进制 12
      PROJECT_STATUS_REVIEW_MASK: 二进制 192
      PROJECT_STATUS_TRANSLATE_MASK: 二进制 3
    x-enum-varnames:
    - PROJECT_STATUS_TRANSLATE_MASK
    - PROJECT_STATUS_PROOF_MASK
    - PROJECT_STATUS_LETTER_MASK
    - PROJECT_STATUS_REVIEW_MASK
  dtos.ProjectStats:
    properties:
      lettered_count:
        description: 已嵌字的项目数量
        type: integer
      lettering_count:
        description: 正在嵌字的项目数量
        type: integer
      prooved_count:
        description: 已校对的项目数量
        type: integer
      prooving_count:
        description: 正在校对的项目数量
        type: integer
      published_count:
        description: 已发布项目数量
        type: integer
      reviewed_count:
        description: 已审核的项目数量
        type: integer
      reviewing_count:
        description: 正在审核的项目数量
        type: integer
      total_count:
        description: 总项目数量
        type: integer
      translated_count:
        description: 已翻译的项目数量
        type: integer
      translating_count:
        description: 正在翻译的项目数量
        type: integer
    type: object
  dtos.RefuseApplicationRequest:
    properties:
      application_id:
        description: 申请的 ID
        type: integer
    required:
    - application_id
    type: object
  dtos.RefuseInvitationRequest:
    properties:
      invitation_id:
        description: 邀请的 ID
        type: integer
    required:
    - invitation_id
    type: object
  dtos.TeamBasic:
    properties:
      id:
        description: 团队 ID
        type: integer
      moetran_id:
        description: Moetran ID
        type: string
      name:
        description: 团队名称
        type: string
    type: object
  dtos.UpdateProjectRequest:
    properties:
      description:
        description: 项目描述
        type: string
      project_id:
        description: 项目 ID，必填
        type: integer
      title:
        description: 项目标题，最大长度 40
        type: string
    required:
    - project_id
    - title
    type: object
  dtos.UpdateProjectStatusRequest:
    properties:
      project_id:
        description: 项目 ID，必填
        type: integer
      status:
        description: 新的项目状态，必填
        type: integer
    required:
    - project_id
    - status
    type: object
  dtos.UserBasic:
    properties:
      id:
        description: 用户 ID
        type: integer
      nickname:
        description: 昵称
        type: string
    type: object
  dtos.UserDetail:
    properties:
      email:
        description: 邮箱
        type: string
      id:
        description: 用户 ID
        type: integer
      last_active:
        description: 上次活跃时间
        type: string
      moetran_id:
        description: Moetran ID
        type: string
      nickname:
        description: 昵称
        type: string
      poplar_is_admin:
        description: 是否是 panel 管理员
        type: boolean
      qq_number:
        description: QQ 号
        type: string
      remark:
        description: 备注
        type: string
    type: object
  dtos.WorksetBasic:
    properties:
      id:
        description: 作品集 ID
        type: integer
      moetran_id:
        description: Moetran ID
        type: string
      name:
        description: 作品集名称
        type: string
      team_id:
        description: 所属团队 ID
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: PoplarGrid API 服务器，提供项目、成员等操作功能
  title: PoplarGrid 核心 API 服务器
  version: "1.0"
paths:
  /member/list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组
      parameters:
      - description: 页码，默认值为 1
        in: query
        name: page_serial
        type: integer
      - description: 每页数量，默认值为 10
        in: query
        name: page_size
        type: integer
      - description: 排序方式，默认值为 id_desc，支持 id_asc | id_desc，其他输入无效
        in: query
        name: sort
        type: string
      - description: 所属汉化组 ID
        in: query
        name: team_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.MemberBasic'
            type: array
      summary: 获取成员列表分页
      tags:
      - member
  /project/{id}:
    get:
      description: 获取指定项目的详细信息，包括翻译、校对、嵌字、审核、发布等状态
      parameters:
      - description: 项目 ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ProjectDetail'
      summary: 获取项目详情
      tags:
      - project
  /project/labor/accept:
    post:
      consumes:
      - application/json
      description: 接受邀请加入项目，需提供邀请的 ID
      parameters:
      - description: 接受邀请加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.AcceptInvitationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 接受邀请加入项目
      tags:
      - project_labor
  /project/labor/accept_appli:
    post:
      consumes:
      - application/json
      description: 接受申请加入项目，需提供申请的 ID
      parameters:
      - description: 接受申请加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.AcceptApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 接受申请加入项目
      tags:
      - project_labor
  /project/labor/apply:
    post:
      consumes:
      - application/json
      description: 申请加入项目，需提供项目 ID 和申请的职位
      parameters:
      - description: 申请加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.ApplyProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 申请加入项目
      tags:
      - project_labor
  /project/labor/invite:
    post:
      consumes:
      - application/json
      description: 邀请成员加入项目，需提供成员的 ID、项目 ID 和邀请职位
      parameters:
      - description: 邀请成员加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.InviteMemberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 邀请成员加入项目
      tags:
      - project_labor
  /project/labor/refuse:
    post:
      consumes:
      - application/json
      description: 拒绝邀请加入项目，需提供邀请的 ID
      parameters:
      - description: 拒绝邀请加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.RefuseInvitationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 拒绝邀请加入项目
      tags:
      - project_labor
  /project/labor/refuse_appli:
    post:
      consumes:
      - application/json
      description: 拒绝申请加入项目，需提供申请的 ID
      parameters:
      - description: 拒绝申请加入项目的请求体
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.RefuseApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 拒绝申请加入项目
      tags:
      - project_labor
  /project/list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组；如果要单独查询已发布的项目列表，请使用 /project/published_list
        接口
      parameters:
      - default: 1
        description: 页码，默认值为 1
        in: query
        name: page_serial
        type: integer
      - default: 10
        description: 每页数量，默认值为 10，最大为 100
        in: query
        name: page_size
        type: integer
      - description: 排序方式，0：按 ID 倒序，1：按 updated_at 倒序
        in: query
        name: sort
        type: integer
      - description: 项目状态（位掩码），用于复合查询。例如：1表示翻译中，256表示已发布
        in: query
        name: status
        type: integer
      - description: 项目所属的作品集 ID，默认为空，表示不筛选
        in: query
        name: workset_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.ProjectBasic'
            type: array
      summary: 获取项目列表分页
      tags:
      - project
  /project/proc/create:
    post:
      consumes:
      - application/json
      description: 创建一个新的项目，请求体暂时未确定
      parameters:
      - description: 创建项目的请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 创建项目
      tags:
      - project_proc
  /project/proc/delete:
    delete:
      consumes:
      - multipart/form-data
      description: 删除指定的项目，需提供项目 ID
      parameters:
      - description: 要删除项目的信息
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.DeleteProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 删除项目
      tags:
      - project_proc
  /project/proc/update_info:
    put:
      consumes:
      - multipart/form-data
      description: 更新指定的项目，需提供项目 ID
      parameters:
      - description: 更新的项目信息
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 更新项目
      tags:
      - project_proc
  /project/proc/update_status:
    put:
      consumes:
      - multipart/form-data
      description: 更新指定项目的状态，需提供项目 ID 和新的状态，调用一次只允许更新一个状态
      parameters:
      - description: 更新项目状态的信息
        in: body
        name: body_params
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateProjectStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 更新项目状态
      tags:
      - project_proc
  /project/published_list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组
      parameters:
      - description: 列表查询参数
        in: query
        name: page_serial
        required: true
        type: integer
      - description: 每页数量，默认值为 10
        in: query
        name: page_size
        required: true
        type: integer
      - description: 排序方式，默认值为 id_desc，支持 id_asc | id_desc | poplarity_desc，其他输入无效
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.ProjectBasic'
            type: array
      summary: 获取已发布的项目列表分页
      tags:
      - project
  /project/stats:
    get:
      description: 获取所有项目的统计信息，包括总数、翻译进行/完成、校对进行/完成、嵌字进行/完成，审核进行/完成、发布完成对应数量等
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ProjectStats'
      summary: 获取项目统计信息
      tags:
      - project
  /team/list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组
      parameters:
      - description: 页码，默认值为 1
        in: query
        name: page_serial
        type: integer
      - description: 每页数量，默认值为 10
        in: query
        name: page_size
        type: integer
      - description: 排序方式，默认值为 id_desc，支持 id_asc | id_desc，其他输入无效
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.TeamBasic'
            type: array
      summary: 获取汉化组列表分页
      tags:
      - team
  /user/detail:
    get:
      description: 获取指定用户的详细信息，包括 ID、用户名、头像等
      parameters:
      - description: 用户 ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDetail'
      summary: 获取用户详情
      tags:
      - user
  /user/list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组
      parameters:
      - description: 页码，默认值为 1
        in: query
        name: page_serial
        type: integer
      - description: 每页数量，默认值为 10
        in: query
        name: page_size
        type: integer
      - description: 排序方式，默认值为 id_desc，支持 id_asc | id_desc，其他输入无效
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.UserBasic'
            type: array
      summary: 获取用户列表分页
      tags:
      - user
  /user/my/detail:
    get:
      description: 获取当前登录用户的详细信息，包括 ID、用户名、头像等
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UserDetail'
      summary: 获取当前用户的详细信息
      tags:
      - user_my
  /user/my/projects:
    get:
      description: 获取当前登录用户参与的所有项目列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.ProjectBasic'
            type: array
      summary: 获取当前用户的项目列表
      tags:
      - user_my
  /user/my/teams:
    get:
      description: 获取当前登录用户所属的所有汉化组列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.TeamBasic'
            type: array
      summary: 获取当前用户的汉化组列表
      tags:
      - user_my
  /workset/list:
    get:
      description: 注意当列表为空，会返回 null 而不是空数组
      parameters:
      - description: 页码，默认值为 1
        in: query
        name: page_serial
        type: integer
      - description: 每页数量，默认值为 10
        in: query
        name: page_size
        type: integer
      - description: 所属汉化组 ID
        in: query
        name: team_id
        required: true
        type: integer
      - description: 排序方式，默认值为 id_desc，支持 id_asc | id_desc | poplarity_desc，其他输入无效
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.WorksetBasic'
            type: array
      summary: 获取工作集列表分页
      tags:
      - workset
swagger: "2.0"
